version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: devenio/marathonapi:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - compose.env
    depends_on:
      - db
    volumes:
      - ./uploads:/usr/src/app/uploads:rw
    networks:
      - marathon-network

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marathon
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - marathon-network

  directus:
        image: directus/directus:latest
        restart: unless-stopped
        ports:
            - 8055:8055
        volumes:
            - ./directus-database:/directus/database
            - ./directus-uploads:/directus/uploads
            - ./directus-extensions:/directus/extensions
        networks:
            - marathon-network
        depends_on:
            - db
        environment:
            SECRET: "replace-with-random-value"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "admin"

            WEBSOCKETS_ENABLED: "true"

            DB_CLIENT: "pg"
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_DATABASE: "marathon"
            DB_USER: "postgres"
            DB_PASSWORD: "postgres"

            # CACHE_ENABLED: "true"
            # CACHE_AUTO_PURGE: "true"
            # CACHE_STORE: "redis"
            # REDIS: "redis://cache:6379"
  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"

volumes:
  pgdata:
    driver: local

networks:
  marathon-network:
    driver: bridge