version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: devenio/marathonapi:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - compose.env
    depends_on:
      - db
    volumes:
      - ./uploads:/usr/src/app/uploads:rw
    networks:
      - marathon-network

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marathon
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - marathon-network

  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"

volumes:
  pgdata:
    driver: local

networks:
  marathon-network:
    driver: bridge